### ISSUE TITLE
Source code does not compile

### ISSUE THREAD

**Issue by acolombo25** [xManager-v2/xManager-Spotify#10]
The source code on this repository actually does not compile.

It has multiple problems, the most obvious is a lot of resources are missing and others are outdated. Also, some other parts in the Java code are missing, and there are classes related to Bluetooth connection (wtf??? why would the app need bluetooth) which are unused.

I find it difficult to trust the compiled version to not contain any malware or anything like that.

**Comment by energ0n** [comment]
Unfortunately the app itself is built with sketchware on an Android device. The source code uploaded here is the exported sketchware project. 

This may change in the future if a proper build environment is obtained and GitHub, Android Studio etc can be used in the build process.

**Comment by acolombo25** [comment]
Well, there's little no point using a git repository this way, to be honest.

He should at least upload all of the files he gets from the export at least the app would be buildable (a lot of files are still missing). Also the diff and the commits would make a lot more sense, because we could see what's actually been modified, rather than containing just files being deleted and re-created.

**Comment by xC3FFF0E** [comment]
We removed and cut unnecessary codes especially languages and theme within the MainActivity.java file. This should resolved the on-going issue in the future. Thanks for the feedback!
