### ISSUE TITLE
songs playing twice?

### ISSUE THREAD

**Issue by synthulhu** [xManager-v2/xManager-Spotify#100]
Ever since I started using xmanager songs have been playing twice. Any clue why this is happening?

**Comment by xC3FFF0E** [comment]
The issue with Spotify app is not tied up with xManager app.

GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
