### ISSUE TITLE
App ztop working, manager unable to load properly?

### ISSUE THREAD

**Issue by Tridente04** [xManager-v2/xManager-Spotify#103]
Hi! 

I notice that my spotify returned to old regular add music today, I tried reinstalling the app serveral time but no result. Please help!

Thanks,
Kien
![Screenshot_20220409-131955_xManager](https://user-images.githubusercontent.com/34959790/162590443-76fd9e63-337c-4ec7-ab80-dcf7444d3560.jpg)

**Comment by Tridente04** [comment]
The screen endlessly load as shown on the screenshot

**Comment by JetpackJackson** [comment]
I'm having the same issue.

**Comment by fukwho** [comment]
Same problem

**Comment by mjg36710** [comment]
I was having that same issue. I ended up reinstalling. Now I am stuck on downloading Spotify. I click on download and an ad pops up. I wait until the reward is granted but it just sits at 0%.

**Comment by fukwho** [comment]
I have  solved the problem at least for now. Force stop the app and open it again. Maybe it still shows it's refreshing, but try to press other buttons (it shows it's refreshing although you can use the app)

**Comment by xC3FFF0E** [comment]
Hi there.

# REASONS WHY xManager KEEPS LOADING:
* One of your installed app is/are blocking firebase to fetch files.
* No Google Play Services.
* Geolocation (firebase is not available within your region).
* Ad-Blockers (disallowing any google or firebase api).
* Connectivity.

# SOLUTIONS:
* Use a VPN.
* Reopen xManager and try again.
* Install Google Play Services.
* Disable any apps that might interfer xManager from fetching database.

# IF THE ISSUES PERSISTS:
* Visit our Telegram Support Group and grab the latest mod build there. Admins and suport users might be able to assist you in details as well.
