### ISSUE TITLE
Android Auto not working 

### ISSUE THREAD

**Issue by boraacer** [xManager-v2/xManager-Spotify#104]
The spotify app does not appear in the Android auto menu on the car screen

I can still play music using my phone screen though 

Samsung Galaxy s20 Ultra 
Android 12
Spotify Amoled version 8.7.10.1262 (ARM64-V8A)

**Comment by dnwong42** [comment]
Try enabling unknown sources in AA on your phone. Open AA and click version 10 times to access developer options.

**Comment by boraacer** [comment]
Thank you that worked! I'm surprised I couldn't find the answer to that on google.
