### ISSUE TITLE
Downloading file stuck at 0 percent for xManager 3.4

### ISSUE THREAD

**Issue by IamNickerson** [xManager-v2/xManager-Spotify#105]
**Describe the bug**
The latest Spotify version mod when I install with xManager it says downloading file but it is stuck at 0 percent.

**To Reproduce**
1. Go to xManager (Version 3.4)
2. Click on Spotify (Regular)
3. And click on Spotify version 8.7.2020.1261 for (ARM64-V8A)
4. And the error should be that it won't install the file.

**Expected behavior**
The installation is stuck at 0 percent for me.

**Screenshots**
![Screenshot_2022-04-13-04-09-35-31_a5c01c4563cf301fdcc1087d689ebdc7.jpg](https://user-images.githubusercontent.com/61643704/163074425-c6e9b93f-d40f-4ca2-80b5-6529b0f9dbc7.jpg)

**Smartphone (please complete the following information):**
 - Device: oppoA54
 - OS:  Android 11
 - Version of xManager: 3.4
 - Version of Spotify: 8.7.20.1261

**Additional context**
I think there something wrong during the installation process of Spotify in xManager.

**Comment by YashG000** [comment]
Yes I am having the same issue.

**Comment by dumpydev** [comment]
Try using the old version (3.2) worked for me :)

**Comment by IamNickerson** [comment]
Ok sure

**Comment by IamNickerson** [comment]
> Try using the old version (3.2) worked for me :)

Brother thanks a lot man it works @everyone try xmanager 3.2 it downloads the file

**Comment by xC3FFF0E** [comment]
You can also try enabling "Copy URL Mode" in the settings. Though downgrading should do the trick as well. Up to you @dumpydev 👍

**Comment by xC3FFF0E** [comment]
UPDATE: Kindly update to v3.4. Let me know if the issue persists. Thanks!

**Comment by IamNickerson** [comment]
Yeah the issue still persists I can only copy URL mode.

**Comment by IamNickerson** [comment]
Yeah the issue still persists I can only copy URL mode.

**Comment by IamNickerson** [comment]
But xManager 3.2 downloads the file.

**Comment by xC3FFF0E** [comment]
> But xManager 3.2 downloads the file.

Interesting. Thank you for trying each version. At least I have an idea and to which I need to look at.

**Comment by IamNickerson** [comment]
Do you think disabling rewarded ads for xManager 3.3 and 3.4 had a caused the Downloading file stuck at 0 percent happen?

**Comment by dumpydev** [comment]
> Do you think disabling rewarded ads for xManager 3.3 and 3.4 had a caused the Downloading file stuck at 0 percent happen?

No, 
1. I don't think rewarded ads would have an impact on the download.
2. I've tried it on and off and on 3.3 and 3.4 won't work.

**Comment by xC3FFF0E** [comment]
I compare the download manager code that i've used in v3.2 to v3.3 and v3.4. All the same. So i'm not really sure what causes the 0% download issue. In this scenario, copy url mode (which can be activated in the setings) will somehow do the work.

**Comment by xC3FFF0E** [comment]
Since the manager app is open-source as well as our API, I think there's no reason for me (as the dev) and to our team to hide such things especially with the links if all of them can be view publicly. So it's the same thing downloading inside the manager app or outside.

**Comment by IamNickerson** [comment]
Oh okay 👍

**Comment by IamNickerson** [comment]
Still Occuring

**Comment by Pratyay360** [comment]
any solution ?? happening on my realme 9 4g too.
