### ISSUE TITLE
downloading songs for offline listening on spotify

### ISSUE THREAD

**Issue by n35h0** [xManager-v2/xManager-Spotify#107]
**Describe the bug**
I can't download playlists on spotify, the rest of the mod is great, but I can't use spotify without downloading the songs, because I'm offline most of the time I listen to music.

**Smartphone:**
 - Device: Huawei P30 lite
 - OS: android 10

**Comment by userliluzibert** [comment]
Yeah, only solution for that I found is [Spotiflyer](https://github.com/Shabinder/SpotiFlyer/). It would be nice if the devs happen to find a solution for this.

**Comment by n35h0** [comment]
so spotiflyer works? and is it safe?

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
