### ISSUE TITLE
API Token Expired

### ISSUE THREAD

**Issue by SteadyStatus21** [xManager-v2/xManager-Spotify#109]
**Describe the bug**

**To Reproduce**
I cannot open the app

**Expected behavior**
I wanted to open the app to check for updates. 

**Screenshots**
![Screenshot_20220425-134317_xManager](https://user-images.githubusercontent.com/73841304/165144301-e2c231af-46bb-4abf-a939-95babda64899.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 5a] Samsung Galaxy S20+ 5G
 - OS: [e.g. Android 9] Android 12
 - Version [e.g. 3.2] 12

**Additional context**
App keeps flashing "API Token Expired" and "No API Response, try again later"

**Comment by xC3FFF0E** [comment]
Thanks for reporting. Working on it and should be resolve on the next update.

**Comment by SteadyStatus21** [comment]
Thank you!

**Comment by xC3FFF0E** [comment]
Kindly update to v3.5. This should fixed the known issue. Thanks!
