### ISSUE TITLE
Premium feature (offline downloads) not working

### ISSUE THREAD

**Issue by RadRagnaroK** [xManager-v2/xManager-Spotify#11]
When I press the download button in a playlist, it highlights for a few seconds.and goes back, without downloading anything.
I could really use offline music play.

**Comment by pimpontitit** [comment]
Same for me.

I hope it will be fixed.

Thanks

**Comment by energ0n** [comment]
> When I press the download button in a playlist, it highlights for a few seconds.and goes back, without downloading anything.
> I could really use offline music play.

Issues are for xManager-specific reports only and not to be used for Spotify mod issues.
