### ISSUE TITLE
Premium functionality broken on update

### ISSUE THREAD

**Issue by A6uh** [xManager-v2/xManager-Spotify#110]
On update from v3.1 to v3.4 and 8.7.20.1261, premium functionality remains broken regardless of "Disable Rewarded Ads" being enabled or disabled. 

Previously (on v3.1), premium functions would be locked and I would be prompted to purchase premium if "Disable Rewarded Ads" was disabled. On enabling that toggle, premium functions would return and the prompts would stop. This includes things like the ability to edit playlists and other functions.

I was able to resolve the issue by leaving 8.7.20.1261 installed, downgrading back to v3.1, opening xManager, disabling rewarded ads, uninstalling v3.1, then finally reinstalling v3.4. 
So now I'm on v3.4 and 8.7.20.1261 with premium functions working. I'm not entirely sure which part fixed it, but those are the steps I followed.

 Device Model: BE2028
 OS: Oxygen OS 11.0.5.BE86AA (Android 11)

Ps: If there was a way to keep premium functions and leave rewarded ads on for you guys, that would be preferred. I wouldn't mind having the ads if I was still able to use the other functions. But without those functions, I might as well just be running the stock app.

**Comment by xC3FFF0E** [comment]
Disable Rewarded Ads is not tied up with our Spotify patches. Usually to resolve these non-functioning premium features, you'll just need to reopen the app after you successfully install it. If that doesn't work, you can force stop the app else, try reinstalling or using any of the cloned versions.

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
