### ISSUE TITLE
App is just not working, still getting ads and no Premium features

### ISSUE THREAD

**Issue by CommonStarguy** [xManager-v2/xManager-Spotify#111]
**Describe the bug**
When logging in to Spotify after clean install, no Premium features are active.

**To Reproduce**
1. Delete old version and download latest version (as of time of posting 8.7.20.1261 (ARM64-VBA))
2. Install new version (allow download from source)
3. Log in and check app to see if Free or Premium layout

**Expected behavior**
App should remove ads and banner for Premium, play any song and unlimited skips

**Screenshots**
![Screenshot_20220426-214506_xManager](https://user-images.githubusercontent.com/83615968/165444101-1aab69aa-2068-411b-9fe0-7f1d1d429911.jpg)
![Screenshot_20220426-220018_Gallery](https://user-images.githubusercontent.com/83615968/165444103-7c10bca1-445e-4a12-a15f-9c0c1827fa17.jpg)
![Screenshot_20220426-214648_Spotify](https://user-images.githubusercontent.com/83615968/165444106-9b769340-766a-4733-9f5a-ce88458dbf67.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9 (Pie)
 - Version 3.4

**Additional context**
Wanted to switch from APKMODY since it kept crashing, so I did a clean install of Spotify through xManager. The last time I used xManager was over a month ago, but the same problem happened. Thought it was fixed now, but not sure why my phone just rejects it.

**Comment by xC3FFF0E** [comment]
Usually to resolve these non-functioning premium features, you'll just need to reopen the app after you successfully install it. If that doesn't work, you can force stop the app else, try reinstalling.

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
