### ISSUE TITLE
Splash screen loop in v3.4

### ISSUE THREAD

**Issue by DallasBelt** [xManager-v2/xManager-Spotify#113]
**Describe the bug**
When opening the app, the xManager splash screen shows repeatedly with no chance of interacting with the app, even when minimizing it.

**To Reproduce**
1. Just open xManager
2. See error

**Expected behavior**
The splash screen have to show once, after opening the app.

**Screenshots**
Please see [here](https://drive.google.com/file/d/1RRhTPjlVD18eu5gvSnQOi9J0dxHM0IzD/view?usp=drivesdk).

**Smartphone (please complete the following information):**
 - Device: Xiaomi Poco X3 Pro
 - OS: Arrow OS 12
 - Version: 12

**Additional context**
I just updated with the built-in updater.

**Comment by xC3FFF0E** [comment]
Kindly update to v3.5. This should fixed the known issue. Thanks!
