### ISSUE TITLE
The newest version of xmanager (3.5)

### ISSUE THREAD

**Issue by Henraee** [xManager-v2/xManager-Spotify#114]
**Describe the bug**
A clear and concise description of what the bug is.when downloading the newest versions of spotify off of xmanager no matter what version of the latest file I downloaded the app wouldnt have the premium features 

**To Reproduce**
1. Go to 'the newest version of xmanager 
2. Click on '.either of the latest versions of the spotify apk
3. Scroll down to 'to the latest versions and install either of the versions 

**Expected behavior**
I expected to have the spotify premium featurrs
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy j2 
 - OS: [android version 8.1.0
 - Version [Samsung expirance version 9.5

**Additional context**

**Comment by xC3FFF0E** [comment]
Have you try force closing the app after installing? That should resolve the issue.
