### ISSUE TITLE
Error occured when analizing packet

### ISSUE THREAD

**Issue by Fergusonnn** [xManager-v2/xManager-Spotify#115]
**Describe the bug**
When downloading Spotify im getting "Error occured when analizing packet" error. I don't have unmodded Spotify installed and i tried installing every version, no one was working

**Screenshots**
![Screenshot_20220508-231715](https://user-images.githubusercontent.com/105175668/167316162-935161bb-94e8-48ff-924d-fa12ec893b87.png)

**Smartphone (please complete the following information):**
 - Device: LG K50
 - OS: Android 10
 - Version 3.5

**Additional context**
Help pls

**Comment by ReduxFlakes** [comment]
Try to install the ARMEABI-V7A version or the V8A

**Comment by xC3FFF0E** [comment]
Download the appropriate cpu/arch base on your device. It might have been you're downloading Arm64-v8a.

**Comment by Fergusonnn** [comment]
I downloaded EVERY version and NO ONE worked.

**Comment by xC3FFF0E** [comment]
Try installing the cloned version.
