### ISSUE TITLE
app for windows

### ISSUE THREAD

**Issue by VarunBanka** [xManager-v2/xManager-Spotify#118]
hey!!!, plese make this app for windows as well.

**Comment by IamNickerson** [comment]
No
Dont

**Comment by IamNickerson** [comment]
Use android app.

**Comment by xC3FFF0E** [comment]
Unfortunately, we don't have any plan making a windows version of the app.

**Comment by VarunBanka** [comment]
> > Unfortunately, we don't have any plan making a windows version of the app.
> 
> How are you even gonna make it even?

If u r making for windows 11, it's easy. Wsa can do it and u don't need anything to do. It's basically a way to run android apps in windows. But to make it officially optimization and available for windows 10 and 7 without emulators, u guys need to code in c# or vsc
