### ISSUE TITLE
"Cant Open File" Using Copy URL Mode (xManager 3.5) (With any Chromium Browser)

### ISSUE THREAD

**Issue by IamNickerson** [xManager-v2/xManager-Spotify#119]
**Describe the bug**
When the file is downloaded with Copy URL Mode it seems that it cant open the file.
**To Reproduce**
1. Go to 'xManager 3.5 '
2. Click on 'The latest version of Spotify (8.7.30.1221) and click on the Copy URL'
3. Go use any Chromium web browser and paste in the link and download the file and click on it
4. See error.

**Expected behavior**
It will say in down Cant Open File in the Chrome Browser.

**Screenshots**
![IMG_20220516_071411](https://user-images.githubusercontent.com/61643704/168514028-a62a796b-dc61-4b9d-bd99-f17182e987d2.jpg)

**Smartphone (please complete the following information):**
-Device: oppoA54
-OS: Android 11
-Version of xManager: 3.5
-Version of Spotify: 8.7.30.1221
**Additional context**
Could be network traffic or maybe during the process of downloading the file.

**Comment by IamNickerson** [comment]
I will paste the link the link also https://cutt.ly/jHzFkZv

**Comment by xC3FFF0E** [comment]
Go to your file manager app/downloads folder then install the apk there. That should do the work.

**Comment by IamNickerson** [comment]
> Go to your file manager app/downloads folder then install the apk there. That should do the work.

Alright what about the people who are using a chrome web to open the apk?
