### ISSUE TITLE
Spotify Download stuck at 0% in 3.5 update

### ISSUE THREAD

**Issue by snipershot713** [xManager-v2/xManager-Spotify#121]
Spotify download is stuck at 0% in xmanager app

1. Installed xmanager 3.5 from Github 
2. Allowed 'All media access'
3. Downloading the ARM64-V8A file.
4. Downloading is stuck at 0%

**Comment by xC3FFF0E** [comment]
If it stuck at 0%, try to download it manually. By using the Copy Url then paste it to any of your browser app.

**Comment by lkipo** [comment]
> 

The URL is not working, in my case at least
