### ISSUE TITLE
Greek letters are not displayed as they should 

### ISSUE THREAD

**Issue by officiallor** [xManager-v2/xManager-Spotify#123]
**Describe the bug**
Greek letter Ππ is displayed as p in a circle, Μμ is displayed as "Q" and Ωω as "ff"

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Greek language'

**Smartphone (please complete the following information):**
 - Device: Mi8
 - OS: Android 10
 - Phone language: English

**Comment by xC3FFF0E** [comment]
Hi there. The Greek translation might probably old. If you want to submit your Greek translation, please follow this: https://github.com/xManager-v2/xManager-Spotify#for-contributors-011822

Thanks!
