### ISSUE TITLE
stopping the music

### ISSUE THREAD

**Issue by flickers0** [xManager-v2/xManager-Spotify#124]
When I press the play button for spotify nothing pops up for me to turn it off or change the song it stays the same on the widget the app the and the pull down notification bar so i essentially have to uninstall the app to stop it this only sometimes happens but it's anoying to have to reinstall it almost everytime I use it sorry if this sounds like a 50 year old yelp review for a bad Starbucks cookie

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
