### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by rakleed** [xManager-v2/xManager-Spotify#125]
**Is your feature request related to a problem? Please describe.**
xManager Spotify icon looks inconsistent compared to other apps

**Describe the solution you'd like**
Make an adaptive icon

**Describe alternatives you've considered**
N/A

**Additional context**
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by xC3FFF0E** [comment]
This should be added on the new update (v3.6). Thanks!
