### ISSUE TITLE
Now Playing notification is not dismissed even after pausing the music.

### ISSUE THREAD

**Issue by shashankreddy999** [xManager-v2/xManager-Spotify#127]
**Describe the bug**
Now Playing notification is not dismissed even after pausing the music.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start playing any music
2. Open the notification area
3. Pause the music
4. Swipe to dismiss the now playing notification, it doesn't go away, acts like a sticky notification

**Expected behavior**
When the Now playing notification is paused and swiped, it should be dismissed.
![bug report image2](https://user-images.githubusercontent.com/47607726/170177417-3ab128d1-a670-4b83-92df-28312157b315.jpeg)
![Bug report image1](https://user-images.githubusercontent.com/47607726/170177423-17f9276e-2a0d-4e05-9366-8a2f513bf6ad.jpeg)

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Oneplus 7t
 - OS: Android 10
 - Version Not sure

**Additional context**
This is my first bug report, I hope I haven't made any mistakes.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
