### ISSUE TITLE
Light mode request

### ISSUE THREAD

**Issue by Trsier** [xManager-v2/xManager-Spotify#132]
Have the devs considered implementing light mode? Would be really great if the mod had one.

**Comment by xC3FFF0E** [comment]
If you're looking for a light/lite version of the Spotify, kindly check Balatan's Lite Mods. Thanks!

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
