### ISSUE TITLE
All downloads stuck at 0%

### ISSUE THREAD

**Issue by Erek1** [xManager-v2/xManager-Spotify#133]
When I try to download any of the versions (AMOLED/Regular) it gets stuck at 0% and doesn't do anything. My device is a Samsung Galaxy A53 5G and I've tried with Wi-Fi and Data. I've also tried downloading older versions of Spotify or Xmanager and still doesn't work.
Anyone has the same problem or knows how to solve it?

**Comment by krando259** [comment]
I also have the 0% download problem, got round it using the copy link function and opening the tinyURL in Chrome. Hope this helps

**Comment by Erek1** [comment]
I have tried the copy link method but chrome doesn't let me get to the website. (Image in spanish)
![Screenshot_20220605-111822_Chrome](https://user-images.githubusercontent.com/106881190/172043870-ce4d295e-d8c4-4fea-8ee2-a0104fdb4468.jpg)

**Comment by krando259** [comment]
> I have tried the copy link method but chrome doesn't let me get to the website. (Image in spanish) ![Screenshot_20220605-111822_Chrome](https://user-images.githubusercontent.com/106881190/172043870-ce4d295e-d8c4-4fea-8ee2-a0104fdb4468.jpg)

If you click the advanced options at the bottom are you able to click the equivalent of "Proceed Anyway"?

**Comment by xC3FFF0E** [comment]
All tiny urls should be updated by now. Try to redownload again. Thanks!

**Comment by Erek1** [comment]
No, it doesn't let me

**Comment by Erek1** [comment]
> All tiny urls should be updated by now. Try to redownload again. Thanks
I tried now and both the copy link and the download itself work for me
Thanks for fixing the issue and for the app ;)

**Comment by Erek1** [comment]
> All tiny urls should be updated by now. Try to redownload again. Thanks!

ok so i tried and the app works fine except there are still limited skips. I tried the AMOLED version and the regular

**Comment by AbbasSrour** [comment]
Have you tried changing the download directory, cause I had the same problem and changing the directory fixed it.

**Comment by Erek1** [comment]
Yeah its now fixed thanks :D

**Comment by xC3FFF0E** [comment]
> Have you tried changing the download directory, cause I had the same problem and changing the directory fixed it.

You mean changing the download directory from the Apk Location?

**Comment by AbbasSrour** [comment]
> > Have you tried changing the download directory, cause I had the same problem and changing the directory fixed it.
> 
> You mean changing the download directory from the Apk Location?

Yes if I remember correctly it was "emulated/0/xmanager" or something, trying to download the spotify apk will stay stuck to 0% although the apk size shows up in the download popup. Changing the directory to something like downloads fixed the problem, Maybe it was because xmanager didn't create the directory upon the download request, I checked now their is a directory called xmanager, but I don't remember if it was their when I tried downloading the apk days ago.

**Comment by xC3FFF0E** [comment]
> > > Have you tried changing the download directory, cause I had the same problem, and changing the directory fixed it.
> > 
> > 
> > You mean changing the download directory from the Apk Location?
> 
> Yes if I remember correctly it was "emulated/0/xmanager" or something, trying to download the Spotify apk will stay stuck to 0% although the apk size shows up in the download popup. Changing the directory to something like downloads fixed the problem. Maybe it was because xmanager didn't create the directory upon the download request, I checked now there is a directory called xmanager, but I don't remember if it was there when I tried downloading the apk days ago.

Awesome thanks! I'll pin point this and will work on it on the next update.

**Comment by faezen** [comment]
It will be awesome if the "download link" could be copied to clipboard when tapping download. It's annoying when you see 2 ads and then the download is stuck.

**Comment by xC3FFF0E** [comment]
> It will be awesome if the "download link" could be copied to clipboard when tapping download. It's annoying when you see 2 ads and then the download is stuck.

Yup. I've been thinking about it as well. Expect for this feature to be added on v3.7.

**Comment by ryayayaan** [comment]
> Have you tried changing the download directory, cause I had the same problem and changing the directory fixed it.

how do you change it?
