### ISSUE TITLE
[Request] Enable Landscape Mode In xManager

### ISSUE THREAD

**Issue by Jaladhjin** [xManager-v2/xManager-Spotify#134]
When using xManager on a tablet it will only operate in portrait mode.

Could an allow rotation/landscape mode please be added?

Would be very grateful.

Thank you for your work on the project!

**Comment by xC3FFF0E** [comment]
Hi there. Thanks for requesting a feature. Landscape support is now added on v3.7 (Take Note: This feature might be buggy as of the moment although it will work just fine.). Let me know what think. Thanks!

**Comment by Jaladhjin** [comment]
Works beautifully on an Android 11 SM-T510 didn't notice any buggy vibes.

Looks great thanks very much I for one really appreciate it! 😁👍
