### ISSUE TITLE
Limited skips on amoled version

### ISSUE THREAD

**Issue by Salmiakkiii** [xManager-v2/xManager-Spotify#135]
Can only skip 6 times before i get the error message notifying that i can't skip anymore.

**Comment by xC3FFF0E** [comment]
Usually to resolve these non-functioning premium features, you'll just need to reopen the app after you successfully install it. If that doesn't work, you can force stop the app else, try reinstalling.

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
