### ISSUE TITLE
xmanager is broken after updating to the latest version

### ISSUE THREAD

**Issue by mininmobile** [xManager-v2/xManager-Spotify#139]
**Describe the bug**
after updating xmanager, the app opened to a black screen and would not start no matter how long i waited. previously installed version was 3.6 and it was working just fine. i tried uninstalling the app and directly installing the apk from github but that also didn't work either. going back to 3.6 and everything is back to normal except now i am scared i will absent mindedly update the app to the broken version again lol

**To Reproduce**
1. download and install apk from latest release
2. open xmanager
3. wait at black screen
4. app not responding message

**Expected behavior**
i would expect the app to open as normal

**Screenshots**
![Screenshot_20220615-020955_xManager.png](https://user-images.githubusercontent.com/17964901/173710367-ea2f19cb-3a80-46d2-babf-590014096e27.png)
![Screenshot_20220615-021002_Trebuchet.png](https://user-images.githubusercontent.com/17964901/173710375-40763ca5-f66c-4ac5-afbc-2daad01955da.png)

**Smartphone:**
 - Device: samsung galaxy s10e (exynos)
 - OS: android 12
 - ROM: lineage os 19 (microg build)
 - Version 3.7

**Comment by xC3FFF0E** [comment]
Some users also report the exact same issue. I'm looking into it right now and might come back once it is fix. Thanks!

**Comment by xC3FFF0E** [comment]
UPDATE: xManager v3.7-1 [Hot Fixed] should be available to download by now. Let me know if the issue persists. Thanks!

**Comment by mininmobile** [comment]
issue is fixed, i could even update from inside 3.6. good work :)
