### ISSUE TITLE
App not working

### ISSUE THREAD

**Issue by arnavjindal** [xManager-v2/xManager-Spotify#14]
After opening the app, app is buffering indefinitely.
This was after new Spotify version notification came, and I clicked it. 
I have tried reinstalling, checking network connection. 
Probably Manager is not able to connect with the server to retrieve data about latest Spotify.

**Comment by TheEpicFlame** [comment]
I have this issue and so does my friend. I think this is affecting everyone l.

**Comment by arnavjindal** [comment]
Issue fixed
