### ISSUE TITLE
I want to download music from Spotify 

### ISSUE THREAD

**Issue by Dovla07** [xManager-v2/xManager-Spotify#140]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xC3FFF0E** [comment]
Downloading tracks/albums/playlist are server-sided.

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
