### ISSUE TITLE
Ads still play when streaming to a device

### ISSUE THREAD

**Issue by WmeLuna** [xManager-v2/xManager-Spotify#142]
**Describe the bug**
I was streaming to my stereo and it started to give me ads 

**To Reproduce**
1. stream to a device
2. listen to music and wait for an ad

**Expected behavior**
no ads

**Smartphone (please complete the following information):**
 - Device: moto g power (2020 model, sofiar)
 - OS: Havoc os 4.16 (android 11)
 - Version 3.7

**Additional context**
i tried to switch playlist as the ad was playing and once the ad finished it shuffled like 8 times before it played

**Comment by xC3FFF0E** [comment]
When casting or using Spotify Connect the audio is no longer sourced from the Spotify mod but instead handled directly by the Spotify API. Free accounts will get ads. You can avoid ads on external devices by connecting your Android device to them via line-out cable or Bluetooth.

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
