### ISSUE TITLE
Latest version has a playlist skipping bug

### ISSUE THREAD

**Issue by gameinn1** [xManager-v2/xManager-Spotify#151]
**Describe the bug**
Issue happens on latest 8.7.44.968 but not 8.7.36.923

Play a playlist. When the phone screen goes off and then idle playing for 2-3 minutes (skipping song with earbuds double tap) causes the playlist to start from the beginning almost without fail. Verified on both google pixel buds and samsung galaxy buds pro. Seems random when it will skip correctly or not.

**To Reproduce**
1. Play a playlist and start on say song 4
2. Turn phone screen off deliberately or wait till idle screen turnoff
3. Listen for 2-3 minutes then try to skip song with earbuds double tap
4. Spotify will go back to the first song in the playlist instead of song 5

**Expected behavior**
The app would play song 5 not song 1

**Smartphone (please complete the following information):**
Xiaomi Redmi Note 10 Pro
Latest software

**Additional context**
Downgrading to 8.7.36.923 seems to work. Did not try it extensively but skipping worked for 4 songs in a row while being idle for 2-3 minutes.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
