### ISSUE TITLE
xManager Spotify doesn't launch 

### ISSUE THREAD

**Issue by Domicele** [xManager-v2/xManager-Spotify#152]
After the update of the launcher my xManager Spotify doesn't seem to launch.I updated the Spotify to the newest release and its not launching like just stuck on the logo and blank screen. how do i fix it? it happened after updating xManager and Spotify

**Comment by Domicele** [comment]
> After the update of the launcher my xManager Spotify doesn't seem to launch.I updated the Spotify to the newest release and its not launching like just stuck on the logo and blank screen. how do i fix it? it happened after updating xManager and Spotify

also downgrade doesn't work

**Comment by heartlog** [comment]
You can try to reinstall **x manager** and **xspotify**..
Give files and storage permission to x manager and download Spotify..
## Then, if Spotify don't open even then ...
Then clear data and relog in to your account..

**Comment by Domicele** [comment]
> You can try to reinstall **x manager** and **xspotify**..
> Give files and storage permission to x manager and download Spotify..
> ## Then, if Spotify don't open even then ...
> Then clear data and relog in to your account..

it fixed by itself after another update
