### ISSUE TITLE
2 second delay when pausing, delay when tapping through seek bar as well.

### ISSUE THREAD

**Issue by dongltron** [xManager-v2/xManager-Spotify#153]
When tapping on the seek bar, there is a short delay not present in the normal app. More frustratingly, there is a solid 2 second delay when tapping the pause button before the music actually stops.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
