### ISSUE TITLE
Doesn't show 'Now Playing' UI 

### ISSUE THREAD

**Issue by creativrss** [xManager-v2/xManager-Spotify#154]
**Describe the bug**
When Spotify is idle for some time, and I go back to play a song. Song starts to play but doesn't show "Now Playing" UI nor in the app neither on notification panel.
And I have to force close and reopen everytime to fix this!

**Expected behavior**
I expect the Spotify app to work normally!

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: VIVO S1 Pro
 - OS: Android 12 
 - Version: 8.7.48.1062 Amoled Black

**Comment by thiswastheonlyavailableusername** [comment]
Same here

**Comment by creativrss** [comment]
Which version solved the issue?

**Comment by thiswastheonlyavailableusername** [comment]
The previous: 8.7.44.968

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
