### ISSUE TITLE
[Feature Request] Change Spotify Country Content

### ISSUE THREAD

**Issue by GodTaisaku** [xManager-v2/xManager-Spotify#156]
Is it possible we can like change our IPs so we can discover music of that specific country. For example if i set it to Japan. The Trending Now or New Music Friday section would now be only Japanese Music.

**Comment by xC3FFF0E** [comment]
As of the moment we don't have any plans adding such features inside the Spotify app. We're keeping it as it is, unlocking premium and A//B features only.

And also, GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
