### ISSUE TITLE
The unlimited skips and other stuff isnt working.

### ISSUE THREAD

**Issue by FreverZ** [xManager-v2/xManager-Spotify#157]
The unlimited skips and other stuff isnt working.

I tried installing both regular and amoled versions, on both the ARMEABI-V7A and ARM64-V8A and with neither of them it worked.
(My phone is a Galaxy S7)

**Comment by heartlog** [comment]
What ?
It's working fine on my Galaxy s7 ..
You can try to reinstall x manager and so do Spotifyx.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
