### ISSUE TITLE
Downloads get deleted

### ISSUE THREAD

**Issue by Lolmerkat** [xManager-v2/xManager-Spotify#158]
I'm on the newest version (amoled) using WiFi and have downloaded some podcasts but they do not seem to be saved as I had to download some multiple times over. Also the downloaded episodes do not show up in my library if I'm completely offline.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
