### ISSUE TITLE
"New Episodes" Playlist Doesn't Work - Crashes On Tap

### ISSUE THREAD

**Issue by NBA613** [xManager-v2/xManager-Spotify#160]
**Describe the bug**
Tapping "New Episodes" playlist completely crashes the app. Latest Mod v8.7.48.1062

**To Reproduce**
1. Tap "My Library"
2. Tap "New episodes"
3. App Crashes

**Expected behavior**
Playlist should open and show new podcast episodes.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 13 Beta 4
 - Spotify Mod Version 8.7.48.1062

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
