### ISSUE TITLE
Unable to download/activate downloads 

### ISSUE THREAD

**Issue by Chungoos** [xManager-v2/xManager-Spotify#163]
I tried to download a playlist (ver. 8.7.48.1062), and it didnt want to so i checked the settings and downloads were deactivated so I tried to activate it but it didnt let me.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
