### ISSUE TITLE
Unable to download my playlist

### ISSUE THREAD

**Issue by Unidentifieduser21** [xManager-v2/xManager-Spotify#164]
I have tried downloading 2 of the latest versions of Spotify on my phone that runs android 12. After I log in to my account, I go to download my playlist but the download button didn't do anything. I had 1 song that was in podcast format and that was the only song it downloaded. So then I removed the podcast and tried downloading the playlist again. The download button didn't do anything again. I even went in the app permissions and allowed storage but that didn't seem to do anything.

Please look into this problem and try your best to fix it.

**Comment by JeanLeShiba** [comment]
Downloading sounds or podcasts isn't something that you can't do client side, so it's not possible even with a mod.

**Comment by Unidentifieduser21** [comment]
> Downloading sounds or podcasts isn't something that you can do client side, so it's not possible even with a mod.

**Comment by Unidentifieduser21** [comment]
So it isn't possible to download any songs on this modded version of Spotify

**Comment by Alternatifx** [comment]
you need premium subscription to download song even with modded apk

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
