### ISSUE TITLE
Spotify crash when clicking 'new episodes' 

### ISSUE THREAD

**Issue by GhostOfJericho72** [xManager-v2/xManager-Spotify#165]
**Describe the bug**
When clicking on 'new episodes', the app crashes to my homescreen. This happened every time. Tried all but reinstalling so far. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'My Library'
2. Click on 'New Episodes''
3. ~~Scroll down to~~
4. ~~See error~~

**Expected behaviour**
To not crash

**Screenshots**
https://user-images.githubusercontent.com/90412368/184501181-10ec0667-7605-4c9d-99d7-df0d63013571.mp4

**Smartphone (please complete the following information):**
 - Device: [OnePlus 6t]
 - OS: [Android 11]
 - Version [11.1.2.2]

**Additional context**
 - Spotify App Version [8.7.48.1062]
 - Restarts don't work
 - Haven't tried reinstalling yet.

**Comment by NBA613** [comment]
#160

**Comment by GhostOfJericho72** [comment]
@NBA613 
Apologies, I didn't look hard enough for a duplicate issue. Sorry, mate.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
