### ISSUE TITLE
Take original Spotify Downloads 

### ISSUE THREAD

**Issue by khaledmoayad** [xManager-v2/xManager-Spotify#166]
**Is your feature request related to a problem? Please describe.**
is there a way for me to be able to use my existing spotify downloads on the app?

**Describe the solution you'd like**
I'd like to be able to use my existing downloads instead of having to redownload over 9gb of music

**Describe alternatives you've considered**
i guess i could have to redownload 9gb of data

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
