### ISSUE TITLE
unwanted Automatic pause

### ISSUE THREAD

**Issue by khaledmoayad** [xManager-v2/xManager-Spotify#167]
**Describe the bug**
the app keeps pausing for no reason

**To Reproduce**
if I press back or navigate to anything like in a playlist or search bar or basically anything, it pauses automatically 

**Expected behavior**
pause when I press pause

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy s10
 - OS: Android 12
 - Version: 8.7.48.1062

**additional info**
this happens completely randomly, one time I launch the app, the other it's fine

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
