### ISSUE TITLE
 Voice Search Doesn't Work

### ISSUE THREAD

**Issue by IvyAnnette** [xManager-v2/xManager-Spotify#168]
Voice search will not receive any commands in the app, and outside the app (assistant) doesn't point to the right song

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram** (Support): https://t.me/SpotifyModSupport
