### ISSUE TITLE
mod 8.7.48.1062 (ARM64-V8A) does not work on Samsung A52s 5G

### ISSUE THREAD

**Issue by nicovoni** [xManager-v2/xManager-Spotify#170]
on Samsung A52s 5G maybe the mod does not work, I say this because spotify is in the free version

**Comment by FadeMind** [comment]
https://www.reddit.com/r/Piracy/comments/twcdsy/comment/i3f7dfw/?utm_source=reddit&utm_medium=web2x&context=3

Update xManager.

Login to Spotify.

Force-stop Spotify.

Done.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
