### ISSUE TITLE
Request for spotify lite app.

### ISSUE THREAD

**Issue by Haimu-ad** [xManager-v2/xManager-Spotify#171]
Hi, I want you to make a mod of Spotify lite app too. Using Spotify is a pain in ass for me as it takes so much time to open and playing a song takes even longer since the internet speed is very bad here. My internet speed hardly crosses 2 kb/s it's always like that here. Spotify lite works very well here with that speed but I don't want to listen to ads. I am attaching the screenshot for your reference.
![Screenshot_2022-08-19-13-15-47-89_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/56254164/185571003-39acb223-830c-4200-ab01-286034b70ffc.jpg)

Thanks !

**Comment by Haimu-ad** [comment]
![IMG_20220819_132657](https://user-images.githubusercontent.com/56254164/185573642-6a65a5c7-2646-484c-8e02-855c79665ac5.jpg)


As you can see in the screenshot the speed is 0.1 kbps(look at the top right corner) and the max it reaches is 2 kbps. It's almost impossible to play any song in Spotify with this speed. I have used "Spotify lite" and I didn't have much problem with playing songs in it except ads.  

Therefore, I request you to please make a mod for Spotify lite app too.

Thanks !

**Comment by xC3FFF0E** [comment]
As of the moment we don't have any plans adding any Spotify Lite.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
