### ISSUE TITLE
Add Google Home/Nest support

### ISSUE THREAD

**Issue by samymsa** [xManager-v2/xManager-Spotify#172]
It seems like the Google Nest Audio is launching the Spotify App using a free account.

The app works perfectly, no ads, until you say something to the Google Nest, like : 
- "Hey Google, turn on the music"
- "Hey Google, next song"

Then ads start popping.

It would be great to remove ads even when using the Google Nest Audio.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
