### ISSUE TITLE
Android auto doesnt work

### ISSUE THREAD

**Issue by sblfc** [xManager-v2/xManager-Spotify#174]
**Describe the bug**

**To Reproduce**
1. Play song
2. connect to android auto

**Expected behavior**cability to search and skip songs, ect

**Smartphone (please complete the following information):**
 - Devicee.galaxy fold 3
 - OS: android 12

**Comment by Hendrick4life** [comment]
Would love this feature as well, currently looking for workarounds

**Comment by weirdal3333** [comment]
Pretty sure this is an issue on Google's side. They removed support for the official Spotify app on Google maps too!

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
