### ISSUE TITLE
Port Spotify patches to reVanced patches

### ISSUE THREAD

**Issue by jr1221** [xManager-v2/xManager-Spotify#176]
I'd like to start by saying this is a great project and thank the devs for making modded spotify a reality.

However, the obvious downsides of distributing apks are:
 - They could contain malicious code modifications
 - They subject the project to legal risk (see Vanced takedown)

I know this is counterintuitive to the xManager project but the [reVanced patching system](https://github.com/revanced) is quickly maturing to be an on client patcher using pre configured patch files.  I was wondering if there was any interest from the devs in adopting this build system to kind of go open source.  And I understand that there is no need to do that right now, but I would hate to see this project get shutdown and the patches inaccessible.

This is probably a dumb idea but I just brought it up thinking of how extensible and legally immune the reVanced project is.

**Comment by xC3FFF0E** [comment]
We've been patching Spotify app for how many years now and just a year ago we decided to launch its own manager app. We know that reVanced is a great project it's just that it is not the right time to do that. For now, as long as we're active, we'll do the traditional way.

**Comment by jr1221** [comment]
Ok, thanks for the response.
