### ISSUE TITLE
Android TV apk

### ISSUE THREAD

**Issue by weirdal3333** [xManager-v2/xManager-Spotify#177]
**Is your feature request related to a problem? Please describe.**
The normal app does work for streaming on my Amazon fire TV gen 1, but it's basically impossible to navigate the menus when logging in. I have to force-close the app on my phone and then hit play on my remote to get it to play.

**Describe the solution you'd like**
An Android TV APK that supports android 5+ would be beneficial for all those who have android TV boxes.

**Describe alternatives you've considered**
I've tried the prebuilt apps from online, but they don't install or don't remove ads.

**Additional context**
If you make this project revanced compatible, it would probably work seamlessly.

**Comment by xC3FFF0E** [comment]
As of the moment we don't have any plans adding a TV version of Spotify app into xManager.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport

**Comment by TarekHC** [comment]
Just a comment that may be useful for others in the future (feel free to delete if it's not).

By installing the android TV app from the play store, but using it for casting songs from the (modded) Spotify app in your phone, you won't get adds if they don't show in your phone, plus it is way more comfortable to use the phone than the android TV controller.
