### ISSUE TITLE
no internet restriction 

### ISSUE THREAD

**Issue by Fa3l** [xManager-v2/xManager-Spotify#178]
**Is your feature request related to a problem? Please describe.**
So I use internet connection via vpn and Spotify doesn't work with it, it says that it doesn't have an internet connection and that's why I wanted a solution for that.

**Describe the solution you'd like**
The solution would be to add Spotify support to any kind of internet with vpn, vpn hack.

**Describe alternatives you've considered**

**Additional context**
I'm not a programmer, and the internet connection I use is no plan

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
