### ISSUE TITLE
Remove api2.branch.io tracking 

### ISSUE THREAD

**Issue by otelo2** [xManager-v2/xManager-Spotify#180]
**Is your feature request related to a problem? Please describe.**
Ok so I have pihole setup and noticed that my phone in seemingly random periods of time would try to connect to the api2.branch.io url (all attempts blocked by pihole) but all connection attempts happen at least every other second. After searching online I found that the URL is a tracking service and that Spotify was the most likely culprit, and this lines up with my tests.

**Describe the solution you'd like**
Is it possible to remove this tracking pixel or whatever? I understand that this repo isn't the correct place so let me know where would be a better place to suggest this :)

**Describe alternatives you've considered**
The tracking isn't an issue since it is being blocked by pihole already, any other way of blocking connections to that url should work too. However, trying to connect every 2 seconds is very excessive, and I'd rather my phone not waste resources in trying to track me

**Additional context**
Also this reddit post supports the idea that Spotify is the culprit 
https://www.reddit.com/r/assholedesign/comments/x2hm10/i_know_that_i_should_expect_some_tracking_when/
Please let me know if I can help in any way, I'd be happy to :)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
