### ISSUE TITLE
Currently playing bar disappearing

### ISSUE THREAD

**Issue by Fidelityyy** [xManager-v2/xManager-Spotify#181]
In the current spotify version (both regular and amoled) the bar at the bottom of the app, which displays the currently played song, is disappearing. I am not perfectly sure, which actions lead to this bug.

**Comment by Miko0XD** [comment]
Same here, after stopping app and starting it again works normally, untill it's minimized, then the bar disappears

**Comment by MINECODEMATE** [comment]
Same issue here, typically force stopping the app and opening again 1 or 2 times fixes it.

**Comment by SteadyStatus21** [comment]
> Same here, after stopping app and starting it again works normally, untill it's minimized, then the bar disappears

I always have to restart the app, and sometimes Spotify will show a notification saying "Spotify is trying to play..." while attempting to play.

**Comment by pitchtheripoff** [comment]
I had the same issue but it seems to be fixed now. I just restarted the app when it happened though it was pretty annoying.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

**xManager (Spotify) Support Links:**
**•Discord:** https://discord.gg/dnpKn5Wufm
**•Reddit:** https://www.reddit.com/r/xManagerApp/
**•Telegram (Support):** https://t.me/SpotifyModSupport
