### ISSUE TITLE
Occasionally crashes

### ISSUE THREAD

**Issue by Fated2be** [xManager-v2/xManager-Spotify#186]
The app will occasionally crash.

Unable to consistently reproduce, but will sometimes crash after a few seconds of a new song playing.

 - Device: Samsung Galaxy S21 Ultra
 - OS: Android 12  OneUI 4.
 - App Version: 8.7.62.398 ARM64-V8A
![Screenshot_20220922_113251](https://user-images.githubusercontent.com/114154610/191792068-98f49963-cd14-47d3-9341-6bc97b76fdf6.jpg)

Phone will occasionally report that Spotify has a bug, and to clear cache to fix it.

**Comment by Fated2be** [comment]
![Screenshot_20220922_113251](https://user-images.githubusercontent.com/114154610/191790011-deae2182-efa9-4c84-b466-68ee2b3eb0f3.jpg)

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.
