### ISSUE TITLE
Voice typing disabled in Spotify search 

### ISSUE THREAD

**Issue by IvyAnnette** [xManager-v2/xManager-Spotify#188]
Keyboard voice typing greyed out when "Search" selected

1. Use Samsung keyboard
2. Select "Search" at the bottom

![Screenshot_20220924-230311_Spotify](https://user-images.githubusercontent.com/95110516/192128120-a7618ca2-ac11-48ea-b65b-09befd0a68e7.jpg)

 - Device: S22
 - OS: Android 12
 - Version: latest version AMOLED

Gboard works fine, but not Samsung voice typing for some reason. Also, Samsung voice typing works fine for searching in "Library" on Spotify.

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.

**Comment by Volderex** [comment]
> This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing. 

not helpful👎
