### ISSUE TITLE
Some kind of themer/theme repo option would be cool, like the ones Aliucord and BetterDiscord have 

### ISSUE THREAD

**Issue by GundamPilotV** [xManager-v2/xManager-Spotify#189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rihaq** [comment]
Sure use revanced manager https://github.com/revanced/revanced-patches/tree/main/src/main/kotlin/app/revanced/patches/spotify/layout/theme

**Comment by xerta555** [comment]
@GundamPilotV You want to theme Spotify app or the xManager app itself ?

**Comment by GundamPilotV** [comment]
> @GundamPilotV You want to theme Spotify app or the xManager app itself ?

The Spotify app itself

**Comment by xerta555** [comment]
> > @GundamPilotV You want to theme Spotify app or the xManager app itself ?
> 
> The Spotify app itself

So the patche's devs will have to perform it and let the choice for the final user in xManager app.
Or you can try Substratum theme(s), root needed in this case.

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.
