### ISSUE TITLE
[Enhancement] Custom APK

### ISSUE THREAD

**Issue by Gam3rrXD** [xManager-v2/xManager-Spotify#190]
I don't really know if xmanger is locally patching but if it is is it possible for us to load apks for it like new apks. A feature revanced manager has?

**Comment by its0x08** [comment]
It downloads apks from dropbox.

**Comment by energ0n** [comment]
> I don't really know if xmanger is locally patching but if it is is it possible for us to load apks for it like new apks. A feature revanced manager has?

This is not something xManager will be doing. Closing.
