### ISSUE TITLE
Showing "14 Days Trial Has Been Ended"

### ISSUE THREAD

**Issue by nerdsuryansh** [xManager-v2/xManager-Spotify#191]
I was using spotify and suddenly a **advert** came up and then i **forced stop** the app so it can work again but suddenly this time a screen came up said "14 Days Trial Has Been Expired Please Purchase Premium" and this was really unexpected from a spotify mod.

**Screenshots**

Here Are Some Screenshots :-

![Screenshot_2022-10-01-22-29-49-167_com.spotify.music.jpg](https://user-images.githubusercontent.com/113819548/193420419-8152ad7a-85ce-4129-99c9-556ceda18fd2.jpg)

![Screenshot_2022-10-01-22-18-57-499_com.spotify.music.jpg](https://user-images.githubusercontent.com/113819548/193420421-de81ddd7-42b2-4616-8dc2-61ef27337773.jpg)

**My Device Specifications**

 - Device: Redmi Note 9 Pro Max
 - OS: Android 11
 - Version: MIUI 12.5.6.0

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.
