### ISSUE TITLE
Unknown device connected!

### ISSUE THREAD

**Issue by Imagoathere** [xManager-v2/xManager-Spotify#192]
Why does the Spotify suddenly have random devices connected to it? 
It is pretty annoying because I have like 2 different  phone connected at random times when I am listening :(

**Comment by whitenoisy** [comment]
This happened to me when I was listening songs on my laptop and my phone connected to it suddenly too. 

Just clear the recent apps from the phone which you don't want to listen Spotify in.

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.
