### ISSUE TITLE
Material You Icon for Android 13

### ISSUE THREAD

**Issue by SpicyPTV** [xManager-v2/xManager-Spotify#193]
Android 13 allows for apps to have icons where the colours adapt and change depending on the colours of the wallpapers. I would really appreciate if this was included in xSpotify as it would be a cool feature.

**Comment by LovecraftianGodsKiller** [comment]
I second this. Please add a Material You Icon for Android 13. Not only for the manager but for xSpotify as well

**Comment by xC3FFF0E** [comment]
Added Material You (M3) but no Dynamic Colors. Lets wait for the rewrite release of the xManager app very soon! For the meantime, kindly update to v4.3 to see the changes. Thanks!
