### ISSUE TITLE
ManagerX 4.0 fails to retrieve any versions to install. 3.9 Works

### ISSUE THREAD

**Issue by Shituation** [xManager-v2/xManager-Spotify#195]
**Describe the bug**
ManagerX 4.0 fails to retrieve any versions to install. 3.9 Works. 
No version is shown under any of the menus.

**Smartphone (please complete the following information):**
 - Device: [SM-N970F]
 - OS: [Android 12]
 - Version [4.0]

**Comment by sharpgolden** [comment]
Try clearing cashe and using vpn.
It worked for me, the app refused to download versions for 3 days until I gave up and used vpn.

**Comment by Shituation** [comment]
Using 3.9 is a better solution since it just works.

**Comment by energ0n** [comment]
Download issues are often due to network not supporting the links used for hosting. Changing network (wifi <-> mobile) or VPN is recommended. xManager is now on 4.2 and only latest build is supported.

**Comment by Shituation** [comment]
And what links are those if you are so kind? what domains are being blocked? to at least check the problem on my side.
I also used wifi and mobile. 
If you continue using those people will start having issues and will have to drop the use of the app.
