### ISSUE TITLE
Removed telemetry and analytics?

### ISSUE THREAD

**Issue by ghost** [xManager-v2/xManager-Spotify#196]
Hi.

I started using this version of spotify, and I fucking love it! Thanks for the hard work.

After checking some logs from NextDNS, it seems that this version of spotify connects to way less spyware domains than the official one.  
Did you remove the parts that send diagnostic/analytics data to spotify? Would this improve privacy aswell?
Thanks

**Comment by its0x08** [comment]
Care to share proof?

**Comment by its0x08** [comment]
Maybe NextDNS screenshot and a setuo explanation.

**Comment by its0x08** [comment]
Btw if the app uses IP instead of domain it won't trigger a DNS lookup so it won't show on your DNS logs!
And secondly it can use firebase as C2 sever to control infected phones if it is a malware..
Firebase offers everything, if not more, that is needed for a C2!
🤷🏻‍♂️

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.

**Comment by its0x08** [comment]
Cool way of closing issues @energ0n 🫡🫡
Shows the authority you have around here.

**Comment by Kncuk** [comment]
Hi, I also found out some privacy concerning element of this, this was taken before any spotify is installed. 
![image](https://user-images.githubusercontent.com/79404196/205481123-34088dd2-ab49-4831-8eba-a0138a4f0e60.png)
The tracking utility used here is [Tracker Control](https://github.com/TrackerControl/tracker-control-android)
