### ISSUE TITLE
Downloading File stuck at 0%

### ISSUE THREAD

**Issue by arlbibek** [xManager-v2/xManager-Spotify#2]
For some reason xManager is not able to download the spotify apk. Whenever I try to download the apk, it shows the DOWNLOADING FILE... popup in the app with 0% progress. The progress won't change (increase) even after some time hence, no apk file is downloaded. :(
For the record it was working fine previously. 
Also, 
Thank you so much for the app, 
I love it.

**Comment by levente99** [comment]
I have the same issue. Did you find the solution?

**Comment by arlbibek** [comment]
Hey man, I didn't find a solution per se, I just updated the app and it worked. 
The current version of the app doesn't have the mentioned issue (at least for me).

**Comment by levente99** [comment]
Okay then i try that, thank you for the help!
