### ISSUE TITLE
Make an IPA for iPhones.

### ISSUE THREAD

**Issue by yodaluca23** [xManager-v2/xManager-Spotify#203]
**Is your feature request related to a problem? Please describe.**
Their are no open source, ad-free Spotify IPA's for iPhone. Their are also very few closed source no ad Spotify IPA's really the only two are just Spotilife and Sposify, both of these are closed source. They could potentially have viruses and/or keyloggers.

**Describe the solution you'd like**
I would like xManager to make a open source xManager version for iPhone, and to make an IPA installer for jailbreaked users and a simple WebApp that just downloads the Spotify IPA directly for non-jailbreaked users who have a limited amount of App ID's.

**Describe alternatives you've considered**
Instead of making a webapp just post the Spotify API's directly to GitHub for non-jailbreaked users.

**Additional context**
I recently got AltStore on my phone I got it to get free YouTube and Spotify I easily found uYou+ (I know it's not 100% open source but the part that's not is made by a notorious tweaker in the community) but was shocked to be unable to find ANY open sourced Spotify IPA's...

**Comment by yodaluca23** [comment]
You could also host a "third-party source" on the AltStore to make it more easy to install with the AltStore, and also automatically update through the AltStore.

More info [here](https://faq.altstore.io/patreon/beta-access/sources)

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.
