### ISSUE TITLE
car thing

### ISSUE THREAD

**Issue by hsl1** [xManager-v2/xManager-Spotify#204]
Please enable car thing option in next version updates.
Thanks.

![258](https://user-images.githubusercontent.com/11902467/196642066-4414f5ad-dd39-48a1-ad9e-70938919a3dd.jpg)

**Comment by EaterComputer** [comment]
Would be very interesting if car thing was compatible with Car Thing. The Car Thing has recently been hacked, so If anything is stopping xmanager to work from the Car Thing's end, it may be possible to bypass.

https://npjohnson.github.io/Spotify-Car-Thing-Root/

**Comment by energ0n** [comment]
This repo is for specifically for xManager and not Spotify/Spotify mod issues/requests. Closing.
