### ISSUE TITLE
Crashing for Podcasts

### ISSUE THREAD

**Issue by HunterAPI** [xManager-v2/xManager-Spotify#205]
**Describe the bug**
It keeps crashing every time I play an episode of a podcast.

**To Reproduce**
Go to any podcast's episodes and play them.

**Expected behavior**
Not crashing

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE
 - OS: Android 12 One UI 4.1
 - Version 8.7.70.553 (ARMEABI-V7A)

**Additional context**
After I clear cache, clear data, uninstall and reinstall. It works for the first time and when I reopen it, it crashes.

**Comment by Prn-Ice** [comment]
Same here, podcasts not working.

**Comment by Everett115** [comment]
I am having the same issue

**Comment by HunterAPI** [comment]
Try downloading the `(ARM64-V8A)` version and see if that also crashes, because that seems to fix it for me.
