### ISSUE TITLE
Option to edit songs from the queue

### ISSUE THREAD

**Issue by MMHJIA** [xManager-v2/xManager-Spotify#206]
The queue drawer is amazing but with one small flaw, there is no way to rearrange or edit or remove song(s) from the queue, if that feature could be added it would have been great, loving the github file though

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport
