### ISSUE TITLE
Search function is not working.

### ISSUE THREAD

**Issue by Schemate** [xManager-v2/xManager-Spotify#207]
Whenever i click on search option it starts loading and after some time it shows no internet connection 

 - Device: [Realme 8]
 - OS: [e.g. Android 12]
 - Version [4.14.186+]
 - app version [8.7.70.553]
![Screenshot_2022-11-01-10-37-12-19_305a1a3985c21ffed1ac8d6efbd1fa75](https://user-images.githubusercontent.com/94690281/199163513-d5b22201-b8b9-4704-b2e4-e33fdb343661.jpg)

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport
