### ISSUE TITLE
Notification can't be expanded - can't read.

### ISSUE THREAD

**Issue by Iaotle** [xManager-v2/xManager-Spotify#210]
After installing the important notification pops up, but the text doesn't fit and the notification can't be dragged down to expand it. Makes it pretty useless. "After installing open..."

**Comment by mortein-powerkiller** [comment]
Can be read in the landscape mode.![Screenshot_20221105-215710_GitHub.jpg](https://user-images.githubusercontent.com/111918023/200130493-d014ec83-689e-4461-9f28-da0ca313b2ff.jpg)

**Comment by xC3FFF0E** [comment]
Should be fixed now on the latest version (v4.2) thanks to @zankyr
