### ISSUE TITLE
Telegram In-App Sync (Update...) Problem

### ISSUE THREAD

**Issue by LarryHopp3r** [xManager-v2/xManager-Spotify#217]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  Samsung S10e
- Android Version:  12
- ROM Version:  OneUI 4.1 stock
- xManager Version: 4.1
```

### 📝 Description

1.In the background is Spotify opened.
2.Then I open up Telegram Application
3.The first line writes "Updating..." in the conversation list
4.Cannot finish update.
5.When i close the Spotify, then it works in Telegram.
...

**Comment by isMehrdad** [comment]
same here

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport
