### ISSUE TITLE
Does it work with the Quest 2?

### ISSUE THREAD

**Issue by BleamX** [xManager-v2/xManager-Spotify#219]
### Description of the new feature / enhancement

I just wanted to know if the app could run on the quest 2

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport
