### ISSUE TITLE
support for friends activity

### ISSUE THREAD

**Issue by liukliukliuk** [xManager-v2/xManager-Spotify#220]
### Description of the new feature / enhancement

the updated official version of spotify has now support for friends' activity. i'd like to know when this feature will be available

**Comment by rezahashemi372** [comment]
😃😃

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport

**Comment by liukliukliuk** [comment]
This is not a request for a feature for spotify, and it's also not a server problem. Their updated application provides this, and your client does not.
