### ISSUE TITLE
Add mods for Spotify Tv

### ISSUE THREAD

**Issue by A-74** [xManager-v2/xManager-Spotify#221]
### Description of the new feature / enhancement

- 1.No ads(visual and video)
- 2.Premium features(skips and others ones in android mod)
- 3.Upgrade to premium button removed

### why?
Although you can use spotify normal app on TV it's lot cumbersome and take lot of space and keeps a cache history which will eventually fill up storage and need to clear them manually from android/data/com.spotify.music folder..it's a pain
SO PLEASE HELP!

**Comment by xC3FFF0E** [comment]
For now, we don't have any plans adding Spotify TV on xManager app.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport

**Comment by foco76** [comment]
Can you say why?I really need it,thank you!

**Comment by DarkCrypt** [comment]
I found an old tv mod still working on Android TV 10 you can try.

**Comment by GALVATRON-GALVATRON** [comment]
> I found an old tv mod still working on Android TV 10 you can try.

Do share a link for that

**Comment by DarkCrypt** [comment]
> Do share a link for that

[XDA](https://xdaforums.com/t/apk-mod-spotify-android-tv-ad-free.3948656/)

**Comment by GALVATRON-GALVATRON** [comment]
Thanks but the Version: 1.9.0 stopped playing for me hence I'm here , no worries lemme give it an other try !

**Comment by DarkCrypt** [comment]
You're right. It's not working. Might be the end of the road now. I think there's a few other possible mods but I don't know if they work.

**Comment by GALVATRON-GALVATRON** [comment]
Alright, do share an update if you find any luck with that. Cheers ✌️
