### ISSUE TITLE
App startup crash ver. 4.2

### ISSUE THREAD

**Issue by AndiDink00x** [xManager-v2/xManager-Spotify#225]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Poco X3 Pro  
- Android Version: 12.1
- ROM Version: LineageOS 19.1 (latest build) 
- xManager Version: 4.2
```

### 📝 Description

Done a clean install of newly version of xManager 4.2 and the app crashes

**Comment by amd64fo** [comment]
me too ，I can't open this software. I'll flash back at one point.

**Comment by bloatmode** [comment]
Same issue on my POCO F3 with LineageOS 19.1

**Comment by xC3FFF0E** [comment]
Hi everyone. Sorry for the late hot-fixed. If you downgraded to v4.1, you can update to v4.2 via OTA else you can redownload the new v4.2 apk at releases section. Please let me know if the issue persists. Thanks!

**Comment by AndiDink00x** [comment]
issue fixed !q
