### ISSUE TITLE
google account login and selecting language preference for song not working

### ISSUE THREAD

**Issue by thaynos** [xManager-v2/xManager-Spotify#226]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model:  samsung a7 2017
- Android Version:  12.1
- ROM Version:  los 19.1
- xManager Version:  latest
```

### 📝 Description

1. when trying to sign in using google it shows something went wrong
2. when trying to set language preference it shows something went wrong

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport
