### ISSUE TITLE
4.2 offers 30 second ad but no download.

### ISSUE THREAD

**Issue by schwim0341** [xManager-v2/xManager-Spotify#229]
When trying to download/update Spotify, Clicking download presents a 30 second ad, then shows "reward granted" but offers nothing other than install button for the ad product.  There's no download link, no download starts, no way to get to the download file shows.  Clicking the "x" by reward granted closes the ad to show the xmanager main page.  Clicking download again presents another 30 second ad, Rinse and repeat.

How do you get to the spotify apk?

**Comment by JakoDel** [comment]
Same issue, the download link displays a "Not found" in the browser

**Comment by rabodecouve** [comment]
Same here. Doesn't matter what version of xManager I'm using, the file for the apk can't be accessed via xManager or by pasting the URL (error 404). This for the Amoled version. The regular one doesn't install through the app (it stays on 0.0% forever) and the URL is a long string that takes too long to respond

**Comment by milanchx** [comment]
yeah i have the exact same issue I'm wondering what the fix for it would be

**Comment by dom-ar** [comment]
I believe non of the downloads seems to be working, might be an issue with the server it self.

**Comment by lunarna-gh** [comment]
Related to https://github.com/xManager-v2/xManager-Spotify/issues/228

**Comment by xC3FFF0E** [comment]
All links should be up by now and ready to download. Let me know if the issue persists. Thanks everyone!

**Comment by syahrezank** [comment]
still not working right now

**Comment by energ0n** [comment]
hosting issue sorted.

**Comment by DerPwny** [comment]
I still have the same issue trying to download the Wave patched version
