### ISSUE TITLE
Downloads on app don't work

### ISSUE THREAD

**Issue by misk007** [xManager-v2/xManager-Spotify#230]
### 🧐 Have you fully read the README and viewed similar issues?

- [X] I have read the README
- [X] I have checked older issues, open and closed
- [X] I did a clean install of xManager
- [X] This is an xManager app issue -- NOT a Spotify mod issue

### ℹ Information

```markdown
- Device Model: Poco X3 Pro 
- Android Version: 12
- ROM Version: Stock
- xManager Version: 4.2
```

### 📝 Description

When trying to download any build in the app it says file is unavailable, and this shows up when link is copied.

### 📸 Screenshots

![Screenshot_2022-12-02-00-06-24-507_com android chrome](https://user-images.githubusercontent.com/119637531/205185146-ffa372bb-ff97-4f7d-9a7f-643def03fcf5.jpg)

**Comment by KrychuTM** [comment]
Same problem here.

**Comment by slapjackios** [comment]
Same here. Dropbox seems to be down again.

**Comment by xC3FFF0E** [comment]
Should be up again. Let me know if the issue persists. Thanks!

**Comment by slapjackios** [comment]
Worked for me. Thanks!
