### ISSUE TITLE
Make Spotify Available on Android Auto

### ISSUE THREAD

**Issue by ElDiablo1968** [xManager-v2/xManager-Spotify#231]
### Description of the new feature / enhancement

Spotify does not appear available in Android Auto when downloaded from xManager

Spotify is not available in the hidden apps to choose from when adding to Android Auto Launcher

Spotify is not available in the launcher after it is used (controlled by mobile device during use) through Android Auto.

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/SpotifyModSupport

**Comment by jacobceles** [comment]
Duplicate of #114. 
@ElDiablo1968 : You need to enable unknown sources in Android Auto on your phone. Open AA and click version 10 times to access developer options.

**Comment by ElDiablo1968** [comment]
Thanks! I'll do that!
