### ISSUE TITLE
Keep system font in Spotify app

### ISSUE THREAD

**Issue by xerta555** [xManager-v2/xManager-Spotify#232]
### Description of the new feature / enhancement

Hi

It could be possible to add an option in xManager or directly in Spotify to keep the default system font of the device in Spotify app itself ?

I ask that bcz i don't like the font forced in Spotify app, i prefer the default one of my device.

Thanks in advance if it's possible.

**Comment by energ0n** [comment]
Enhancements suggestions are for xManager only. Anything related to the Spotify app directly is outside the scope of this repo.

**Comment by xerta555** [comment]
> Enhancements suggestions are for xManager only. Anything related to the Spotify app directly is outside the scope of this repo.

Where can i do a request for the Spotify app itself so ?
