### ISSUE TITLE
How to get Album art in wired Android Auto?

### ISSUE THREAD

**Issue by eSkRo32** [xManager-v2/xManager-Spotify#234]
![16705460446631806611280587410644](https://user-images.githubusercontent.com/17524629/206595705-e102eaa2-2926-4359-a40b-66ad92a32b92.jpg)
Hi all  :)
Thanks for your amazing work!

Like title says
How to get Album art in Spotify wired Android Auto?

Tried many Things, but art Just wont appear 🤔

Sorry if I ask in wrong place!
Maybe point me in right direction? 
Thx 👍

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues, request and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

xManager (Spotify) Support Links:
•Discord: https://discord.gg/dnpKn5Wufm
•Reddit: https://www.reddit.com/r/xManagerApp/
•Telegram (Support): https://t.me/xManagerSupport
