### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by iwrsu** [xManager-v2/xManager-Spotify#26]
None of the versions are working, it just freezed when you try to install any version

**Comment by Yhonay** [comment]
I had the same problem. Try opening settings (second icon on the top right) and enabling "cult url mode", then just paste link into a browser and install as a normal apk.

**Comment by dlopez0682** [comment]
> I had the same problem. Try opening settings (second icon on the top right) and enabling "copy url mode", then just paste link into a browser and install as a normal apk.

Is there a way to rename this issue? I had "Unable to parse package" problems with most of the downloaded APKs. This is the only issue that fixed the problem, but I think it's hard to find with a title like "Not Working".
