### ISSUE TITLE
lyrics not loading

### ISSUE THREAD

**Issue by horsain** [xManager-v2/xManager-Spotify#27]
in the three last builds the app has not been able to load lyrics

**Comment by TheVaccin3** [comment]
I have the same problem

**Comment by infekSK** [comment]
Ditto

**Comment by horsain** [comment]
update: it's working for me now, anyone else ?

**Comment by TheVaccin3** [comment]
Yep working for me too now!

**Comment by V3ntus** [comment]
Spotify just released a global lyrics function so that might be what fixed it

**Comment by energ0n** [comment]
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
