### ISSUE TITLE
Spotify Wrapped is Broken

### ISSUE THREAD

**Issue by hackurtaim** [xManager-v2/xManager-Spotify#33]
The stories for Spotify Wrapped is broken , it always shows the download logo , and when the story does load up , it quickly go to the next story and repeat the same issue until the story is over making it unusable for me to watch the story

**Comment by suruaku** [comment]
This happens for me on Android 10 with just plain Spotify (8.6.84.1240) from the play market.

**Comment by energ0n** [comment]
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
