### ISSUE TITLE
Sound quality

### ISSUE THREAD

**Issue by MetalEloi666** [xManager-v2/xManager-Spotify#35]
Hello, the app is great but why can't we get the highest sound quality? There are others apk that offer this feature.
Thanks.

**Comment by oudoulj** [comment]
I have read elsewhere that high fidelity sound is a server-side feature 🤷
xDeezer doesn't have it either, see screenshot.
What other apk are you talking about ?

![Screenshot_20211208-081305](https://user-images.githubusercontent.com/6011092/145165180-722a6d79-5a90-4d06-b7a1-92d504921bac.png)

**Comment by MetalEloi666** [comment]
I think it's this version.
https://iptmod.com/android/spotify-music-apk-premium-mod/

**Comment by MetalEloi666** [comment]
![Screenshot_20211208-063431_Spotify](https://user-images.githubusercontent.com/95734255/145202292-9d4fbce6-b9e3-42e3-b181-6d1bfbd13067.jpg)

**Comment by MetalEloi666** [comment]
![Screenshot_20211208-063423_Spotify](https://user-images.githubusercontent.com/95734255/145202355-be8e0863-59a3-4d59-b28f-b6eb21653fe8.jpg)

**Comment by MetalEloi666** [comment]
My phone is in French. "Très haute" is "Very High".

**Comment by energ0n** [comment]
> My phone is in French. "Très haute" is "Very High".

saying very high and actually giving you very high are 2 different things. you cannot get very high quality without a premium subscription... you're still getting auto or "high" even when it says "very high"

Also, any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
