### ISSUE TITLE
Cant download songs from 'liked songs' playlist

### ISSUE THREAD

**Issue by LittleBlin** [xManager-v2/xManager-Spotify#39]
Hi, I dont know if its intended, but I cant download playlist 'liked songs' which I should (probably). Its only happens with this playlist, since I can download other ones without any problem. If anyone know why plz tell me about it.

**Comment by Kwesty4658** [comment]
You have likely had premium in the past and it is letting you download. Downloading is not possible with this version of Spotify.

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
