### ISSUE TITLE
Discover tab doesn't work anymore

### ISSUE THREAD

**Issue by Cawfee1** [xManager-v2/xManager-Spotify#40]
since the new update it doesn't seem to work

**Comment by vbbehera** [comment]
Yes discover tab is not working

**Comment by JamTarty** [comment]
Same issue here

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
