### ISSUE TITLE
can't change audio quality anymore

### ISSUE THREAD

**Issue by Cawfee1** [xManager-v2/xManager-Spotify#41]
as of this update the audio quality can't be changed, last version I was able to

**Comment by vbbehera** [comment]
I have also same problem I can't set it to very high.

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
