### ISSUE TITLE
Can't play on some speaker devices 

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [xManager-v2/xManager-Spotify#43]
![Screenshot_20220113-093842_Spotify](https://user-images.githubusercontent.com/5219339/149295569-8a301296-6540-41f6-b3f6-4ae80259b2fc.jpg)

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
