### ISSUE TITLE
Can't Download Any Song

### ISSUE THREAD

**Issue by Hichen220** [xManager-v2/xManager-Spotify#47]
Hello, I couldn't download any song in Spotify, the download button doesn't download any song, it just rolls back to where it was and no download starts

**Comment by Kwesty4658** [comment]
Sadly, the download button doesn't work with this version of Spotify.

**Comment by Kwesty4658** [comment]
> when will this be fixed?

Its unlikely to ever be fixed as downloads are server sided feature, none of which work on this version of Spotify

**Comment by Hichen220** [comment]
Can't I use an older version of Spotify?

**Comment by Hichen220** [comment]
so it's pretty much dead

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
