### ISSUE TITLE
Song from Search plays a different song

### ISSUE THREAD

**Issue by oudoulj** [xManager-v2/xManager-Spotify#49]
I'm running **Spotify 8.6.94.306** (regular) installed through xManager on BlueStacks.
If I look up any song with the magnifier icon then when I click a song in that list, **it always plays a totally different track** :-/
Is that a known issue ? thank you !

![spotify_misplayed](https://user-images.githubusercontent.com/6011092/150422288-b02b77dd-5cda-450b-8009-185d75ab5654.gif)

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
