### ISSUE TITLE
Can't install downloaded APKs

### ISSUE THREAD

**Issue by IrkenEngineer** [xManager-v2/xManager-Spotify#51]
Odd issue, genuinely not sure if it's my device or the app itself.

I was able to install a patched APK through XManager on my tablet just fine, but it will not install on my phone. 

The XManager app itself installed just fine and I am able to download the APKs without trouble.

Whenever I hit "install", the Android system shows me the usual pop-up to confirm I want to install. The loading bar moves as it would when installing, but then it simply says, "app not installed." 

I tried using Package Manager on F-Droid to install the APK, and similarly it does not work but the error message displays as "invalid APK" in the Package Manager app.

**UPDATE: It seems Spotify wasn't properly uninstalled. Corrected the issue and it works great.**

**Comment by xznhj8129** [comment]
Spotify is NOT Installed but i get the same "app appears invalid" error on all APKs
