### ISSUE TITLE
Account Access from Russia, Algeria.. 

### ISSUE THREAD

**Issue by yener90** [xManager-v2/xManager-Spotify#53]
What is wrong with this application? I always get messages that there was access around the world. Does this hack my password?

**Comment by energ0n** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.

With that said, xManager does not collect any login information. And the Spotify app only talks directly with Spotify itself. If you are receiving messages about access from other locations it's either related to you using a VPN which changes your location or your account has been compromised in some other way and you should immediately change your password.
