### ISSUE TITLE
Downloading stuck at 84%

### ISSUE THREAD

**Issue by eyeholeman0** [xManager-v2/xManager-Spotify#60]
Both regular version and AMOLED black version get stuck at 84% while downloading (then after some time there's a message saying link unavailable or something and disappears)
Using vpn didn't help either

**Comment by xC3FFF0E** [comment]
It is an issue wih the current hosting although we manually changing it from time to time. If the issue persist in the future, please let us know by checking our support group channel.

**Comment by z8512** [comment]
We do you host files though? Also, why have host only a 'part of code' in github just for marketing?
