### ISSUE TITLE
downloading file stuck at 0 mb

### ISSUE THREAD

**Issue by darkone03** [xManager-v2/xManager-Spotify#61]
**Issue before solution**
I downloaded the latest version of xmanager , but whenever I try to download Spotify on it the download is just stuck at 0 mb
-my Android version is 11
-and miui version is 12.5.5
-my phone is not rooted
-tried disabling mi optimization and the installation
![Screenshot_2022-02-20-20-05-59-930_com.xc3fff0e.xmanager.jpg](https://user-images.githubusercontent.com/94281812/154847921-78d19393-63b4-4043-a2df-ec5aba698234.jpg)

**solution**
just use different net, take hotspot of another guy or girl or gay 
fuck it take switch your net while downloading

**Comment by xC3FFF0E** [comment]
It is an issue wih the current hosting although we manually changing it from time to time. If the issue persist in the future, please let us know by checking our support group channel.
