### ISSUE TITLE
Very High audio quality settings immediately reverting to automatic

### ISSUE THREAD

**Issue by calisonic** [xManager-v2/xManager-Spotify#62]
For either cellular and wifi audio streaming quality settings, if Very High is selected, the selection immediately changes to Automatic. Making Very High un-selectable.  

Thanks

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
