### ISSUE TITLE
The File or link is currently unavailable

### ISSUE THREAD

**Issue by Astralrr** [xManager-v2/xManager-Spotify#68]
Anyone know how to fix this ( yeah I don't know how what else to add here)

https://user-images.githubusercontent.com/100779093/156372601-f19aee5c-727c-48b0-9ee2-c7e3a3e8b4e3.mp4

![Screenshot_20220302-204041_Video Player](https://user-images.githubusercontent.com/100779093/156372722-51a4f763-033e-405c-ae16-1283b32e2bcb.png)

**Comment by alex-sandro92** [comment]
It seems a common network error... have you tried downloading different builds? Or maybe cleaning app's data?

**Comment by Astralrr** [comment]
> It seems a network error... does it stop at the same points? have you tried downloading different builds? or maybe cleaning app's data?

I dont know if It stops at the same point, yes I've tried downloading diffrent builds and yes I've tried cleaning the apps data

**Comment by xC3FFF0E** [comment]
All links should have been updated by now. Visit our Telegram Support Group for further info.

**Comment by Raees-k455** [comment]
Try copying the link and pasting it in browser then download
