### ISSUE TITLE
Battery Drain issue

### ISSUE THREAD

**Issue by beshoyy** [xManager-v2/xManager-Spotify#7]
since i started using Spotify from xmanager i notice a big battery drain and don't know why although this not clear in statistics of my device !!
Phone : redmi note 10
Rom : miui global 12.0.10
![IMG_20210629_022407](https://user-images.githubusercontent.com/86613416/123719436-d02e2d00-d881-11eb-8d78-77da76de852a.jpg)

**Comment by energ0n** [comment]
Github issues are for xManager-related issues and not Spotify. Please use support group for Spotify-related issues. 

But this is most likely an issue with Spotify itself. Perhaps the specific version doesn't "agree" with your phone/rom and not much can be done on our side. A few suggestions... 
-wipe app data, force close the app and hope issue resolves itself
-try a different Spotify version to see if it works better with your specific device
-hope a future update resolves this issue for you

Spotify <-> Phone performance is all down to Spotify itself and your phone/rom.. the mod itself would not alter battery life.
