### ISSUE TITLE
Unusable

### ISSUE THREAD

**Issue by kcdriod** [xManager-v2/xManager-Spotify#70]
I am not able to download app through xmanager at all 
![Screenshot_20220304-122639_xManager](https://user-images.githubusercontent.com/42491726/156714952-28559e04-4018-4f47-8b11-477f8fd2243f.png)

**Comment by roma272007** [comment]
Use version 2.7 until fix

**Comment by xC3FFF0E** [comment]
Kindly update to v2.9 to resolve the issue. Thanks!
