### ISSUE TITLE
Unable to play the full song from playlists.

### ISSUE THREAD

**Issue by mohankumar807** [xManager-v2/xManager-Spotify#72]
I'm able to play the full song from the beginning when I search for a specific song and play. However, for the songs that are already in a saved playlist (for example, Liked Songs), only the song preview is played.

**Comment by spectr1x** [comment]
Yes, I had the same problem when I downloaded the latest version of the AMOLED patch, however the problem went away when I used the previous available version (I could play any song from playlists and there was no premium button).

Best bet I guess is to use the second-to-latest version for now, and hope that the issue gets resolved soon!
