### ISSUE TITLE
Stops Working Sometimes

### ISSUE THREAD

**Issue by JoeyOwen** [xManager-v2/xManager-Spotify#73]
Version: [LATEST] 8.7.4.1056 (ARM64-V8A)
Device: Galaxy A52 5G 

Sometimes while listening and doing other things, Spotify just stops, mostly when it goes to the next song/skipping songs from notification bar, it acts as if the song is paused until I open Spotify 

Battery optimizations are turned off btw

**Comment by xC3FFF0E** [comment]
GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
