### ISSUE TITLE
when we turn on " disable rewarded ads ", we cant see artist photos in library plese fix it thank you

### ISSUE THREAD

**Issue by RaghavanVdy** [xManager-v2/xManager-Spotify#75]

**Comment by xC3FFF0E** [comment]
Disable Rewarded Ads does not tied with Spotify.

GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
