### ISSUE TITLE
divided by zero error when canceling the download 

### ISSUE THREAD

**Issue by winterolym** [xManager-v2/xManager-Spotify#76]
Version: 2.9
Device: Galaxy A50
OS: Android 11

When I cancel the download, the app crashes and if I launch the app again it shows this message.

![Screenshot_20220312-183917_xManager](https://user-images.githubusercontent.com/65142096/158012982-61e942b8-dd04-4518-854a-d1c1c29554b9.jpg)

**Comment by xC3FFF0E** [comment]
Thanks! Will take a look at it.
