### ISSUE TITLE
Installing but it says it's not installed and can't download any versions 

### ISSUE THREAD

**Issue by sprylog** [xManager-v2/xManager-Spotify#8]
![photo_2021-06-30_04-38-11](https://user-images.githubusercontent.com/32218980/123921031-f83e8e80-d95c-11eb-986f-a0e59270b28a.jpg)
![photo_2021-06-30_04-38-12](https://user-images.githubusercontent.com/32218980/123921035-f8d72500-d95c-11eb-9424-3dbe8aaecc87.jpg)
 

i am using a custom rom this one to be exact on a galaxy j5 2015 https://forum.xda-developers.com/t/rom-j500xx-tw-7-1-1-v5-0-seperience-rom-a8-2018-port.3796971/ and it is rooted, it worked on the phone before the rom, but i can't find what is causing the issue and every other app is working fine

**Comment by MrJeffOfficial** [comment]
yeah i have the same problem

**Comment by energ0n** [comment]
Download hosting goes down from time to time. Please use the support group to report such issues in the future... issues can be addressed much faster there.
