### ISSUE TITLE
Xmanager 3.0 is not working on windows subsystem for android but 2.9 works flawlessly

### ISSUE THREAD

**Issue by RaghavanVdy** [xManager-v2/xManager-Spotify#80]

**Comment by 1-minute-to-midnight** [comment]
It's probably because of the safetynet.......and since wsl for android doesn't have support for google services, it lacks safetynet

**Comment by xC3FFF0E** [comment]
Welp that cause some major issues. Anyway, new update is out now. Kindly update to v3.1 to resolve the issue. Thanks!

**Comment by RaghavanVdy** [comment]
Thank you so much for fixing this, i really appeciate that you really care and fix bugs fastly.
