### ISSUE TITLE
[Question] Why SafetyNet?

### ISSUE THREAD

**Issue by Poopooracoocoo** [xManager-v2/xManager-Spotify#81]

**Comment by 1-minute-to-midnight** [comment]
Just leaving a comment here to tell that I too despise safetynet and would like it removed. Sticking to previous version (2.9) for the time-being

**Comment by xC3FFF0E** [comment]
> Just leaving a comment here to tell that I too despise safetynet and would like it removed. Sticking to previous version (2.9) for the time-being

I agree. Not worth implementing in the future updates.

**Comment by jeffersoncheang** [comment]
Hi dev, pardon my illiteracy, may I know which version should I be using? 3.0 vs 3.1? And is Safetynet something I should _avoid_?

**Comment by xC3FFF0E** [comment]
Use the v3.1 as that version is stable and kindly disregard the SafetyNet
feature on that specific version (v3.1), as I already removed that.

The SafetyNet feature was implemented in v3.0 to secure our databases and
apis but due to some errors, i've decided to removed it.

Thanks!,
xC3FFF0E
