### ISSUE TITLE
 xManager with hidden buttons

### ISSUE THREAD

**Issue by DavidBrazSan** [xManager-v2/xManager-Spotify#86]
I tested on two cell phones, they are:

Samsung J200M Android 5.1.1
Samsung SM-G532MT Android 6.0.1

I can install because I know where the buttons are.

![Screenshot_2022-03-21-19-21-47](https://user-images.githubusercontent.com/60136669/159374081-094c2062-8020-43fd-b660-666c29212503.png)
![Screenshot_2022-03-21-19-22-02](https://user-images.githubusercontent.com/60136669/159374087-af776d2b-e006-4dc8-8a38-74e928c9cff2.png)
![Screenshot_2022-03-21-19-22-13](https://user-images.githubusercontent.com/60136669/159374088-fde48ea3-c323-4ff8-9c10-97d2309a5bf8.png)

**Comment by DavidBrazSan** [comment]
The application is updated and i've done everything you said. it doesn't show up yet.

**Comment by DavidBrazSan** [comment]
Fixed the issue. Thank you

**Comment by xC3FFF0E** [comment]
Awesome! Closing this now.
