### ISSUE TITLE
Can no longer disable Rewarded Ads

### ISSUE THREAD

**Issue by A6uh** [xManager-v2/xManager-Spotify#88]
The Disable Rewarded Ads slider no longer works while all the others do. Forcing this to be enabled disables most, if not all, Spotify premium functionality. Such as being unable to edit my playlists, etc.

For the time being I've just downgraded back to an older version, where it worked, as I see no other workaround.

**Comment by Oscillate18** [comment]
> The Disable Rewarded Ads slider no longer works while all the others do. Forcing this to be enabled disables most, if not all, Spotify premium functionality. Such as being unable to edit my playlists, etc.
> 
> For the time being I've just downgraded back to an older version, where it worked, as I see no other workaround.

Swiping on the toggle worked for me

**Comment by xC3FFF0E** [comment]
This issue should be resolve by updating to v3.2.
