### ISSUE TITLE
Version 8.7.10.1262 does not work

### ISSUE THREAD

**Issue by AzreScar** [xManager-v2/xManager-Spotify#89]
I have tried to update form V.8.7.10.1056 to the latest version(V.8.7.10.1262), and every time I have tried it downloads perfectly fine but the none of the features work (no ads, unlimited skips). I don't know if I'm doing anything wrong in updating or if the new version isn't patched yet as I can not find anything that says its not been patched.

The way I'm updating is by completely deleting the old version and updating to the new one from a fresh reinstall.

**Comment by xC3FFF0E** [comment]
Try force stopping or reopening the app to resolve issue. Also GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
