### ISSUE TITLE
Downloading not working

### ISSUE THREAD

**Issue by Birmioh** [xManager-v2/xManager-Spotify#90]
Hello,

Before starting, I really appreciate the work you make on Spotify. I'm using it for my phone and in my car.

The point is I can't use the offline mode because I'm not allowed to use the downloading fonction.

Still need premium to do that. Is that a normal issue cause you don't work on it or you can't fix it?

Thanks

**Comment by jay5656** [comment]
It's normal, no Spotify app will let you download without premium. If they did, they would get in trouble
