### ISSUE TITLE
Will it be possible to add Yandex music to xmanager? From April 1, Spotify stops working in our country. 

### ISSUE THREAD

**Issue by Glazami** [xManager-v2/xManager-Spotify#94]
application, for example, can be taken from telegram alexstranniklite

**Comment by Glazami** [comment]
> you can change your region in spotify settings and continue to use it i thin
it is forbidden

**Comment by xC3FFF0E** [comment]
As of now we don't have any plans adding new variations or patches. xManager is only exclusive for Spotify app.
