### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by senolfndk** [xManager-v2/xManager-Spotify#96]
can you add turkish language

**Comment by Glazami** [comment]
> Why does xManager not have a translation for my language?

xManager translations rely on our users submitting translations to us. Due to time constraints additional language submissions are on pause at the moment. If you are still interested in submitting a translation please visit our support channel to discuss this further.

**Comment by senolfndk** [comment]
ok

**Comment by xC3FFF0E** [comment]
Turkish translation is already available in the xManager app. You can submit an updated translation instead by following this link: https://github.com/xManager-v2/xManager-Spotify#for-contributors-011822. Thanks!
