### ISSUE TITLE
New playlist UI

### ISSUE THREAD

**Issue by Araxeus** [xManager-v2/xManager-Spotify#97]
The new playlist/album ui in 8.7.10.1262
![Screenshot](https://community.spotify.com/t5/image/serverpage/image-id/114365i5F963C7300FBACAD) Changed compared to the older version 8.7.4.1056
![Screenshot](https://user-images.githubusercontent.com/78568641/160567232-228c234f-1985-474c-8510-e10ad8c186dd.jpg)

It doesn't allow free users to select specific songs from the list, its absolutely shit

I've reverted to 8.7.4 but could you maybe fix this in newer versions?

Might be out of scope here but im not sure whats the apk's origin

**Comment by xC3FFF0E** [comment]
Try reopening or clearing the cache and data of the Spotify app after installing. Also GitHub issues for xManager should be used for the xManager app only.
Any and all issues and discussion with Spotify are outside the scope of the xManager repo and should be moved to the telegram or discord support channels.
